# UI Config
ui:
  title: VDI Login
  tag-line: Proxmox VDI
  vdi-icon: vdiicon.ico
  vdi-logo: vdiclient.png
  kiosk: False
  fullscreen: True
  theme: default

debug:
  ini-viewer: False

proxmox:
  authentication:
    auth_backend: pve # pve or pam or whatever is configured on PVE
    auth_totp: False # enable or disable totp field
    tls_verify: False # False or True or path to certificate to verify
  token:
    name: None
    username: None
    value: None
#  SpiceProxyRedirect: False # For if you dont need proxy
#    from: pve1.example.com
#    from-port: 3128
#    to: 10.10.10.100
#    to-port: 3128
  SpiceProxyRedirect: # get from viewing the ini file if not config
    from: pve1.example.com
    from-port: 3128
    to: 10.10.10.100
    to-port: 3128
  show-vm-type: all # lxc or qemu or all

host:
  - name: "Host 1"
    ip: 10.10.10.100
    port: 8006
  - name: "host 2"
    ip: 10.10.10.100
    port: 8006
  # add as much host as you want this will affect the login dropdown

# If you wish to define additional parameters to pass to virt-viewer you may define them here
# More parameter definitions here: https://www.mankier.com/1/remote-viewer
virt-viewer:
  enable-usbredir: True
  enable-usb-autoshare: True